teams = {
    1: 'Las Vegas Raiders',
    2: 'Jacksonville Jaguars',
    3: 'New England Patriots',
    4: 'New York Giants',
    5: 'Baltimore Ravens',
    6: 'Tennessee Titans',
    7: 'Detroit Lions',
    8: 'Atlanta Falcons',
    9: 'Cleveland Browns',
    10: 'Cincinnati Bengals',
    11: 'Arizona Cardinals',
    12: 'Philadelphia Eagles',
    13: 'New York Jets',
    14: 'San Francisco 49ers',
    15: 'Green Bay Packers',
    16: 'Chicago Bears',
    17: 'Kansas City Chiefs',
    18: 'Washington Commanders',
    19: 'Carolina Panthers',
    20: 'Buffalo Bills',
    21: 'Indianapolis Colts',
    22: 'Pittsburgh Steelers',
    23: 'Seattle Seahawks',
    24: 'Tampa Bay Buccaneers',
    25: 'Miami Dolphins',
    26: 'Houston Texans',
    27: 'New Orleans Saints',
    28: 'Denver Broncos',
    29: 'Dallas Cowboys',
    30: 'Los Angeles Chargers',
    31: 'Los Angeles Rams',
    32: 'Minnesota Vikings',
}

team_numbers = {
    'Las Vegas Raiders': 1,
    'Jacksonville Jaguars': 2,
    'New England Patriots': 3,
    'New York Giants': 4,
    'Baltimore Ravens': 5,
    'Tennessee Titans': 6,
    'Detroit Lions': 7,
    'Atlanta Falcons': 8,
    'Cleveland Browns': 9,
    'Cincinnati Bengals': 10,
    'Arizona Cardinals': 11,
    'Philadelphia Eagles': 12,
    'New York Jets': 13,
    'San Francisco 49ers': 14,
    'Green Bay Packers': 15,
    'Chicago Bears': 16,
    'Kansas City Chiefs': 17,
    'Washington Commanders': 18,
    'Carolina Panthers': 19,
    'Buffalo Bills': 20,
    'Indianapolis Colts': 21,
    'Pittsburgh Steelers': 22,
    'Seattle Seahawks': 23,
    'Tampa Bay Buccaneers': 24,
    'Miami Dolphins': 25,
    'Houston Texans': 26,
    'New Orleans Saints': 27,
    'Denver Broncos': 28,
    'Dallas Cowboys': 29,
    'Los Angeles Chargers': 30,
    'Los Angeles Rams': 31,
    'Minnesota Vikings': 32
}


timezone = {80: "America/Boise"}


team_names = [
    "Arizona Cardinals",
    "Atlanta Falcons",
    "Baltimore Ravens",
    "Buffalo Bills",
    "Carolina Panthers",
    "Chicago Bears",
    "Cincinnati Bengals",
    "Cleveland Browns",
    "Dallas Cowboys",
    "Denver Broncos",
    "Detroit Lions",
    "Green Bay Packers",
    "Houston Texans",
    "Indianapolis Colts",
    "Jacksonville Jaguars",
    "Kansas City Chiefs",
    "Las Vegas Raiders",
    "Los Angeles Chargers",
    "Los Angeles Rams",
    "Miami Dolphins",
    "Minnesota Vikings",
    "New England Patriots",
    "New Orleans Saints",
    "New York Giants",
    "New York Jets",
    "Philadelphia Eagles",
    "Pittsburgh Steelers",
    "San Francisco 49ers",
    "Seattle Seahawks",
    "Tampa Bay Buccaneers",
    "Tennessee Titans",
    "Washington Commanders"
]

team_abbreviations = {
    "Arizona Cardinals": "ARI",
    "Atlanta Falcons": "ATL",
    "Baltimore Ravens": "BAL",
    "Buffalo Bills": "BUF",
    "Carolina Panthers": "CAR",
    "Chicago Bears": "CHI",
    "Cincinnati Bengals": "CIN",
    "Cleveland Browns": "CLE",
    "Dallas Cowboys": "DAL",
    "Denver Broncos": "DEN",
    "Detroit Lions": "DET",
    "Green Bay Packers": "GB",
    "Houston Texans": "HOU",
    "Indianapolis Colts": "IND",
    "Jacksonville Jaguars": "JAC",
    "Kansas City Chiefs": "KC",
    "Las Vegas Raiders": "LV",
    "Los Angeles Chargers": "LAC",
    "Los Angeles Rams": "LAR",
    "Miami Dolphins": "MIA",
    "Minnesota Vikings": "MIN",
    "New England Patriots": "NE",
    "New Orleans Saints": "NO",
    "New York Giants": "NYG",
    "New York Jets": "NYJ",
    "Philadelphia Eagles": "PHI",
    "Pittsburgh Steelers": "PIT",
    "San Francisco 49ers": "SF",
    "Seattle Seahawks": "SEA",
    "Tampa Bay Buccaneers": "TB",
    "Tennessee Titans": "TEN",
    "Washington Commanders": "WAS"
}

team_IDs = {
    "Arizona Cardinals": 99999,
    "Atlanta Falcons": 99998,
    "Baltimore Ravens": 99997,
    "Buffalo Bills": 99996,
    "Carolina Panthers": 99995,
    "Chicago Bears": 99994,
    "Cincinnati Bengals": 99993,
    "Cleveland Browns": 99992,
    "Dallas Cowboys": 99991,
    "Denver Broncos": 99990,
    "Detroit Lions": 99989,
    "Green Bay Packers": 99988,
    "Houston Texans": 99987,
    "Indianapolis Colts": 99986,
    "Jacksonville Jaguars": 99985,
    "Kansas City Chiefs": 99984,
    "Las Vegas Raiders": 99983,
    "Los Angeles Chargers": 99982,
    "Los Angeles Rams": 99981,
    "Miami Dolphins": 99980,
    "Minnesota Vikings": 99979,
    "New England Patriots": 99978,
    "New Orleans Saints": 99977,
    "New York Giants": 99976,
    "New York Jets": 99975,
    "Philadelphia Eagles": 99974,
    "Pittsburgh Steelers": 99973,
    "San Francisco 49ers": 99972,
    "Seattle Seahawks": 99971,
    "Tampa Bay Buccaneers": 99970,
    "Tennessee Titans": 99969,
    "Washington Commanders": 99968
}


def team_abbrev(comment):
    for old_name, new_name in team_abbreviations.items():
        comment = comment.replace(old_name, new_name)
    return comment

